### ISSUE TITLE
I need to use TCP on Fastly Compute to connect to a cloud database! But it doesn't have access to it.

### ISSUE THREAD

**Issue by masx200** [fastly/js-compute-runtime#750] opened 2024-04-06 10:09 UTC
I need to use TCP on Fastly Compute to connect to a cloud database!
But it doesn't have access to it.

**Comment by JakeChampion** [comment] 2024-04-06 13:33
I'm closing this issue as this is a duplicate of your issue on https://github.com/fastly/compute-sdk-go/issues/107

**Closed** 2024-04-06 13:33 UTC
