### ISSUE TITLE
Throw error exit code for failed compilation

### ISSUE THREAD

**Issue by williamoverton** [fastly/js-compute-runtime#52] opened 2021-11-18 14:23 UTC
If I compile a syntactically valid javascript file that is still not valid we get a wizer error. However the exit code is 0.

Example input index.js:
```javascript
spaghetti
```

output of `js-compute-runtime --skip-pkg bin/index.js bin/main.wasm`:
```
Exception while evaluating JS: (new ReferenceError("spaghetti is not defined", "<stdin>", 1))
  @<stdin>:1:29
  @<stdin>:1:121

Error: failed to initialize JS

Caused by:
    0: the `wizer.initialize` function trapped
    1: Exited with i32 exit status 1
       wasm backtrace:
           0: 0x3d82a1 - <unknown>!<wasm function 8744>
           1: 0x3d9434 - <unknown>!<wasm function 8760>
           2: 0x1c23a - <unknown>!<wasm function 300>
           3: 0x1bfd5 - <unknown>!<wasm function 298>
           4: 0x1c554 - <unknown>!<wasm function 303>
       
Wizer failed with status: exit status: 1
```

This is the correct error but the status code is 0:
```
...
Wizer failed with status: exit status: 1
 
➜  echo $?
0
```

This makes it impossible for tooling to detect build errors.

**Comment by JakeChampion** [comment] 2021-11-28 16:52
@williamoverton - do you know what version of js-compute-runtime this error occurred on?

I tried to replicate this but unfortunately could not, the exit code I have is 255

```
❯ js-compute-runtime --skip-pkg src/index.js index.wasm
Exception while evaluating JS: (new ReferenceError("spaghetti is not defined", "<stdin>", 1))
  @<stdin>:1:1

Error: failed to initialize JS

Caused by:
    0: the `wizer.initialize` function trapped
    1: Exited with i32 exit status 1
       wasm backtrace:
           0: 0x3d61d5 - <unknown>!<wasm function 6078>
           1: 0x3d7d0c - <unknown>!<wasm function 6088>
           2: 0x402ec - <unknown>!<wasm function 263>
           3: 0x3ffb2 - <unknown>!<wasm function 261>
           4: 0x407a7 - <unknown>!<wasm function 266>

Wizer failed with status: exit status: 1
❯ echo $?
255
```

**Comment by JakeChampion** [comment] 2021-12-04 01:16
@williamoverton I've now confirmed this bug and found the fix for it 👍 

The bug lies within the JavaScript package which unfortunately looks to not be open source. The package creates a child-process for js-compute-runtime but doesn't reflect the exit code of the child process onto the parent process.

The fix for this would be to capture the child-process result object on line 53 of [@fastly/js-compute/js-compute-runtime-cli.js](https://unpkg.com/browse/@fastly/js-compute@0.2.1/js-compute-runtime-cli.js) and apply the status as the process.exitCode, the diff below shows the change required.


```diff
-spawnSync(binaryPath, process.argv.slice(2), {
+const result = spawnSync(binaryPath, process.argv.slice(2), {
  stdio: "inherit",
});
-
+process.exitCode = result.status;
console.log(" ");
```

**Closed** 2022-01-25 17:45 UTC

**Comment by JakeChampion** [comment] 2022-01-25 17:47
@torch2424 - it looks like the fix has not yet been published, do you know when that will be?

**Comment by torch2424** [comment] 2022-01-25 18:43
@JakeChampion Hello! 😄 

Yes, so we're currently in the process of automating our deployments, and our plan was to use this next release to test our Github Action for this.

So, once we get that nailed down, it should be released! If you don't mind me asking, is this fix blocking you on your project?

Let me know, thanks! 😄

**Comment by JakeChampion** [comment] 2022-01-25 18:48
It's not blocking me, I already have the patch applied in my projects 😊
